version: '3.9'
services:
  frontend:
    build: .
    environment:
      - ENV=production
    ports:
      - "80:80"
      - "443:443"
    restart: unless-stopped
    container_name: frontend
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
