version: '3.9'
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ENV=development
      - PORT=80
    ports:
      - "80:80"
      - "443:443"
    restart: unless-stopped
    container_name: frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
