services:
  frontend-dev:
    profiles: ["dev"]
    build:
      context: .
      target: dev
    environment:
      - ENV=development
      - VITE_REACT_APP_LANGUAGE=pt-BR # Disponíveis: pt-BR, it, en-US.
    ports:
      - "127.0.0.1:3001:3001"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    container_name: frontend-dev
    restart: unless-stopped

  frontend:
    profiles: ["prod"]
    build:
      context: .
      target: prod
    environment:
      - ENV=production
    ports:
      - "127.0.0.1:3000:3000"
    container_name: frontend-prod
    restart: unless-stopped
    networks:
      - proxy-network

networks:
  proxy-network:
    external: true
