FROM node:21-alpine3.19 as build-stage

WORKDIR /app

COPY frontend/package*.json ./
RUN npm install

COPY frontend/ .
RUN npm run build

FROM nginx:1.25-alpine

COPY --from=build-stage /app/dist /usr/share/nginx/html

COPY nginx/nginx.conf.production /etc/nginx/nginx.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]