version: '3.9'
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ENV=development
      - VITE_REACT_APP_LANGUAGE=pt-BR # Disponíveis: pt-BR, it, en-US.
    ports:
      - "80:80"
    restart: unless-stopped
    container_name: frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
