services:

  buzin-solutions-front:
    profiles: ["prod"]
    container_name: buzin-solutions-front-dev
    restart: unless-stopped
    build:
      context: .
      target: prod
    environment:
      - ENV=production
    ports:
      - "3000:3000"
    networks:
      - proxy-network

  buzin-solutions-front-dev:
    profiles: ["dev"]
    container_name: buzin-solutions-front
    restart: unless-stopped
    build:
      context: .
      target: dev
    environment:
      - ENV=development
      - VITE_REACT_APP_LANGUAGE=pt-BR # Disponíveis: pt-BR, it, en-US.
    ports:
      - "3004:3004"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - proxy-network

networks:
  proxy-network:
    external: true
